version: '3.6'

services:
   app:
    container_name: laravel10
    restart: always
    build: .
    ports:
      - 82:80
      - 83:83
      - 4040:4040
      - 443:443
    volumes:
      - .:/var/www
    networks:
      - ngrok_network

networks:
  ngrok_network:
    driver: bridge
